PORTNAME=	snmp_passpersist
DISTVERSIONPREFIX=	v
DISTVERSION=	2.1.0
CATEGORIES=	net-mgmt python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	surajravi@gmail.com
COMMENT=	Python client library for Net-SNMP pass persist backend
WWW=		https://github.com/nagius/snmp_passpersist

LICENSE=	GPLv3

RUN_DEPENDS=	net-snmp>=0:net-mgmt/net-snmp

USES=		python

USE_GITHUB=	yes
GH_ACCOUNT=	nagius

USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
