PORTNAME=	empt-host-kerberos
DISTVERSION=	0.1.0
CATEGORIES=	empt
MASTER_SITES=
DISTFILES=

MAINTAINER=	me@svmhdvn.name
COMMENT=	EMPT krb5 host setup
WWW=		https://empt.ca

LICENSE=	UNLICENSE

RUN_DEPENDS=	empt-base:empt/empt-base

USES=		metaport

.include <bsd.port.mk>
