PORTNAME=	msgpack
PORTVERSION=	2.2.0
PORTREVISION=	1
CATEGORIES=	devel

MAINTAINER=	fluffy@FreeBSD.org
COMMENT=	Provides API for communicating with MessagePack serialization
WWW=		https://pecl.php.net/package/msgpack

LICENSE=	BSD3CLAUSE

USES=		php:pecl

.include <bsd.port.mk>
