PORTNAME=	Proc-ProcessTable-Match
PORTVERSION=	0.0.1
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	vvelox@vvelox.net
COMMENT=	Matches a Proc::ProcessTable::Process against a stack of checks
WWW=		https://metacpan.org/release/Proc-ProcessTable-Match

BR_DEPENDS=	p5-Proc-ProcessTable>=0.59:devel/p5-Proc-ProcessTable
BUILD_DEPENDS=	${BR_DEPENDS}
RUN_DEPENDS=	${BR_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
