PORTNAME=	Horde_Service_Facebook
DISTVERSION=	2.0.10
PORTREVISION=	1
CATEGORIES=	www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Facebook client
WWW=		https://pear.horde.org

USES=	horde php cpe
USE_PHP=	simplexml
USE_HORDE_RUN=	Horde_Exception \
		Horde_Http \
		Horde_Translation \
		Horde_Support \
		Horde_Util

.include <bsd.port.mk>
