PORTNAME=	devtodo2
DISTVERSION=	2.2
CATEGORIES=	devel

MAINTAINER=	me@svmhdvn.name
COMMENT=	Tool to effectively maintain todo lists aimed at developers
WWW=		https://swapoff.org/devtodo.html

CONFLICTS_INSTALL=	deforaos-todo tdl todo

USES=		go:modules ncurses readline
GO_MODULE=	github.com/alecthomas/devtodo2

LICENSE=	APACHE20

.include <bsd.port.mk>
