PORTNAME=	cmph
DISTVERSION=	2.0.2
CATEGORIES=	devel
MASTER_SITES=	https://github.com/bonitao/cmph/releases/download/v${DISTVERSION}/

MAINTAINER=	jessekempf@gmail.com
COMMENT=	Minimal perfect hashes for C
WWW=		https://cmph.sourceforge.net/

LICENSE=	LGPL21 MPL11
LICENSE_COMB=	dual
LICENSE_FILE_LGPL21=	${WRKSRC}/LGPL-2
LICENSE_FILE_MPL11=	${WRKSRC}/MPL-1.1

GNU_CONFIGURE=	yes
USES=		libtool pathfix
USE_LDCONFIG=	yes

.include <bsd.port.mk>
