PORTNAME=	timfel-krb5-auth
PORTVERSION=	0.8.3
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	KRB5 for Ruby
WWW=		https://github.com/timfel/krb5-auth

USES=		gem gssapi:mit

.include <bsd.port.mk>
