PORTNAME=	empt-host-mail
DISTVERSION=	0.1.0
CATEGORIES=	empt
MASTER_SITES=
DISTFILES=

MAINTAINER=	me@svmhdvn.name
COMMENT=	EMPT mail host setup
WWW=		https://empt.ca

RUN_DEPENDS=	empt-base:empt/empt-base

LICENSE=	UNLICENSE

USES=		metaport

.include <bsd.port.mk>
