#!/bin/sh

set -eu

org_domain="$(hostname -d)"

j="${PKG_ROOTDIR}/empt/jails/mail"
mkdir -p "${j}"
pkg -r "${j}" install -y -r jail_pkgbase -g 'FreeBSD-*'

zfs create -p \
    -o mountpoint="${j}/var/spool/postfix" \
    zroot/empt/synced/postfix_spool

zfs create -p \
    -o mountpoint="${j}/var/spool/mlmmj" \
    zroot/empt/synced/rw/mlmmj_spool

zfs create -p \
    -o mountpoint="${j}/var/db/cyrusimap" \
    zroot/empt/synced/rw/cyrusimap_db

zfs create -p \
    -o mountpoint="${j}/var/spool/cyrusimap" \
    zroot/empt/synced/rw/cyrusimap_spool

# Generate krb5 keytab
# ==========================
chroot "${PKG_ROOTDIR}/empt/jails/kerberos" \
    kadmin -l add --random-key --use-defaults \
    "smtp/mail.${org_domain}" \
    "imap/mail.${org_domain}" \
    "HTTP/mail.${org_domain}" \

chroot "${PKG_ROOTDIR}/empt/jails/kerberos" \
    kadmin -l ext_keytab --keytab=/tmp/mail.keytab "*/mail.${org_domain}"
mv "${PKG_ROOTDIR}/empt/jails/kerberos/tmp/mail.keytab" \
    "${j}/etc/krb5.keytab"
# ==========================

# Request TLS cert from ACME
# ==========================
acme.sh --home "${PKG_ROOTDIR}/var/db/acme" \
    --issue -d "mail.${org_domain}" \
    --standalone
certdest="/usr/local/etc/ssl/certs"
mkdir -p "${j}/${certdest}"
acme.sh --home "${PKG_ROOTDIR}/var/db/acme" \
    --install-cert -d "mail.${org_domain}" \
    --fullchain-file "${j}/${certdest}/mail.${org_domain}.crt.pem" \
    --key-file       "${j}/${certdest}/mail.${org_domain}.key.pem"  \
    --reloadcmd      "service jail onerestart mail"
# ==========================

sysrc -R "${PKG_ROOTDIR}" syslogd_flags+="-l /empt/jails/mail/var/run/log"

pkg -r "${j}" install -y empt-jail-mail
