PORTNAME=	empt-host-dns
DISTVERSION=	0.1.0
CATEGORIES=	empt
MASTER_SITES=
DISTFILES=

MAINTAINER=	me@svmhdvn.name
COMMENT=	EMPT DNS host config
WWW=		https://empt.ca

LICENSE=	UNLICENSE

USES=		metaport

.include <bsd.port.mk>
